name: Hello World Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Say Hello
      run: echo "Hello, World!"
  
  depended_job:
    needs: [say_hello]
    runs-on: ubuntu-latest

    steps:
      - name: Printing message after Hello World
        run: echo "It's a message from another job 2."
    
    
